// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package server

type Activity struct {
	ID          string        `json:"id"`
	Sid         string        `json:"sid"`
	Sport       string        `json:"sport"`
	Time        string        `json:"time"`
	Athlete     *Athlete      `json:"athlete"`
	Laps        []*Lap        `json:"laps"`
	Trackpoints []*TrackPoint `json:"trackpoints"`
}

type Athlete struct {
	ID         string      `json:"id"`
	Name       string      `json:"name"`
	Alterego   string      `json:"alterego"`
	Activities []*Activity `json:"activities"`
}

type Lap struct {
	Time      string  `json:"time"`
	Duration  float64 `json:"duration"`
	Distance  float64 `json:"distance"`
	Calories  float64 `json:"calories"`
	MaxSpeed  float64 `json:"max_speed"`
	AvgHr     float64 `json:"avg_hr"`
	MaxHr     float64 `json:"max_hr"`
	Intensity string  `json:"intensity"`
}

type NewAthlete struct {
	Name     string `json:"name"`
	Alterego string `json:"alterego"`
}

type TrackPoint struct {
	Time     string  `json:"time"`
	Lat      float64 `json:"lat"`
	Long     float64 `json:"long"`
	Altitude float64 `json:"altitude"`
	Distance float64 `json:"distance"`
	Hr       float64 `json:"hr"`
	Cadence  float64 `json:"cadence"`
	Speed    float64 `json:"speed"`
	Power    float64 `json:"power"`
}
